"""
Project management for the Proof-of-Work Agent.
Handles creating and updating project drafts on Colosseum.
"""

from __future__ import annotations

import os
from typing import Optional
from dataclasses import dataclass
from datetime import datetime

from agent.logger import get_logger
from colosseum.api import ApiError

DEFAULT_TAGS = ["ai", "security", "solana", "autonomous-agent"]


@dataclass
class ProjectUpdate:
    """Represents a project update."""
    timestamp: datetime
    heartbeat_status: str
    forum_activity: str
    task_hash: str
    solana_tx: str
    additional_notes: Optional[str] = None


def build_update_text(result_hash: str, sig: str) -> str:
    """Build the project update text."""
    return (
        "Autonomous report:\n"
        "- Heartbeat synced\n"
        "- Forum engaged\n"
        f"- Task solved hash: {result_hash}\n"
        f"- Solana TX: {sig}"
    )


def default_project_payload() -> dict:
    """Get the default project payload."""
    repo_link = os.getenv("PROJECT_REPO_LINK", "").strip()
    if not repo_link:
        repo_link = "https://colosseum.com/agent-hackathon"
    return {
        "name": "Proof-of-Work Agent",
        "description": (
            "Autonomous agent that reads the Colosseum heartbeat, engages the forum, "
            "and submits proof hashes on Solana devnet."
        ),
        "repoLink": repo_link,
        "solanaIntegration": (
            "Deploys a minimal Anchor bounty program on Solana devnet and submits "
            "proof hashes via submit_work."
        ),
        "tags": DEFAULT_TAGS,
    }


def ensure_project(api) -> None:
    """Ensure project exists, create if not."""
    log = get_logger("colosseum.project")
    try:
        api.get_my_project()
        return
    except ApiError as exc:
        if exc.status != 404:
            raise
    payload = default_project_payload()
    api.create_project(payload)
    log.info("Created project draft.")


class ProjectManager:
    """Manages project updates on Colosseum."""
    
    MODULE = "project"
    
    UPDATE_TEMPLATE = """Autonomous report:
- Heartbeat synced: {heartbeat_status}
- Forum engaged: {forum_activity}
- Task solved hash: {task_hash}
- Solana TX: {solana_tx}
{additional}

---
Generated by POW-Agent
Timestamp: {timestamp}
Cycle: {cycle}"""
    
    def __init__(self, api):
        self.api = api
        self.log = get_logger(self.MODULE)
        self._update_history: list[ProjectUpdate] = []
        self._cycle_count = 0
    
    def _format_update(self, update: ProjectUpdate) -> str:
        additional = ""
        if update.additional_notes:
            additional = f"\nNotes: {update.additional_notes}"
        
        return self.UPDATE_TEMPLATE.format(
            heartbeat_status=update.heartbeat_status,
            forum_activity=update.forum_activity,
            task_hash=update.task_hash,
            solana_tx=update.solana_tx,
            additional=additional,
            timestamp=update.timestamp.isoformat(),
            cycle=self._cycle_count
        )
    
    def update(
        self,
        heartbeat_status: str,
        forum_activity: str,
        task_hash: str,
        solana_tx: str,
        additional_notes: Optional[str] = None
    ) -> bool:
        """Create and submit a project update."""
        self._cycle_count += 1
        
        update = ProjectUpdate(
            timestamp=datetime.utcnow(),
            heartbeat_status=heartbeat_status,
            forum_activity=forum_activity,
            task_hash=task_hash,
            solana_tx=solana_tx,
            additional_notes=additional_notes
        )
        
        update_text = self._format_update(update)
        
        self.log.info(f"Submitting project update (cycle {self._cycle_count})...")
        
        try:
            self.api.update_project(update_text)
            self._update_history.append(update)
            self.log.success("Project update submitted successfully")
            return True
        except Exception as e:
            self.log.error(f"Failed to submit project update: {e}")
            return False
    
    def get_current(self) -> dict:
        """Get the current project from Colosseum."""
        self.log.info("Fetching current project...")
        try:
            project = self.api.get_my_project()
            self.log.success("Current project retrieved")
            return project
        except Exception as e:
            self.log.error(f"Failed to fetch project: {e}")
            return {}
    
    def ensure_exists(self) -> None:
        """Ensure project exists."""
        ensure_project(self.api)
    
    def get_update_history(self) -> list[ProjectUpdate]:
        return self._update_history.copy()
    
    def get_last_update(self) -> Optional[ProjectUpdate]:
        if self._update_history:
            return self._update_history[-1]
        return None
    
    def get_cycle_count(self) -> int:
        return self._cycle_count
